CREATE DATABASE IF NOT EXISTS MoviesDB;
USE MoviesDB;

CREATE TABLE IF NOT EXISTS Director (
    PKDirector INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(100) NOT NULL,
    Age INT,
    Active BOOLEAN NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS Movies (
    PKMovies INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(100) NOT NULL,
    Gender VARCHAR(50),
    Duration TIME,
    FKDirector INT,
    FOREIGN KEY (FKDirector) REFERENCES Director(PKDirector)
);
